url: "https://jeantimothee.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
title: "Timothée Régis" # the name of your site, e.g. ACME Corp.
